<?php
return array(
    'appName'                      => 'KaPow',
    'appVersion'                   => '0.1',
    'siteTitle'                    => array(),
    'templates'                    => array(),
    'menus'                        => array(),
    'sizes'                        => array(),
    'supports'                     => array(),
    'stylesheets'                  => array(),
    'classes'                      => array(),
    'postTypes'                    => array(),
    'widgets'                      => array(),
    'plugins'                      => array(),
    'panel'                        => array(),
    'siteTitleSeparator'           => '&laquo;',
    'templateNameStarting'         => 'tpl-',
    'shouldUseFilterForNavClasses' => true,
    'debugStylesheetAndScripts'    => false,
    'shouldAutoLoadPostTypes'      => false,
    'shouldAutoLoadPlugins'        => false,
    'shouldAutoLoadWidgets'        => false,
    'shouldIncludeKaPowJs'         => false,
    'javascriptVariables'          => array(),
    'dirNameAssets'                => 'assets',
    'dirNameImages'                => 'images',
    'dirNameScripts'               => 'scripts',
    'dirNameStyles'                => 'styles',
    'dirNameXhr'                   => 'xhr',
);